### ISSUE TITLE
Cannot read propery 'results' of null.

### ISSUE THREAD

**Issue by MacMillan13** [brunojs02/react-native-movies-app#2]
![Screenshot from 2020-02-12 17-07-14](https://user-images.githubusercontent.com/18086617/74347613-061c5f80-4dba-11ea-8046-c0d539a3a4da.png)
Hi, please help. @brunojs02  Think that I don't get any response...

**Comment by brunojs02** [comment]
Did u followed the before run instructions?

**Comment by MacMillan13** [comment]
@brunojs02 of course.. I have generated key and url of themoviedb. Don’t understand why don’t get response....

**Comment by brunojs02** [comment]
@MacMillan13 i'll check out

**Comment by MacMillan13** [comment]
@brunojs02 thanks

**Comment by brunojs02** [comment]
![Screenshot_1581524529](https://user-images.githubusercontent.com/7714813/74354855-b7ab9880-4d9a-11ea-89d8-859280de4778.png)
I just run and everything is ok.
Do the following:
Open and change  the file src/hooks/use-fetch.js
// before
api.get(path, { params })
      .then(({ data }) => {
        setResponse(data);
        setLoading(false);
      })
      .catch(() => {
        setLoading(false);
      });
// after
api.get(path, { params })
      .then(({ data }) => {
        console.log('response', data);
        setResponse(data);
        setLoading(false);
      })
      .catch((error) => {
       console.log('error', error);
        setLoading(false);
      });

After run in debug mode and share the console output

**Comment by MacMillan13** [comment]
@brunojs02 Code break before useEffect. I just put console.log like u show and added else one before useEffect and just this one show.

**Comment by brunojs02** [comment]
did u create the config THEMOVIEDB_API_KEY in firebase remote config with your key from themoviedb?

**Comment by MacMillan13** [comment]
@brunojs02 
![Screenshot from 2020-02-12 20-38-31](https://user-images.githubusercontent.com/18086617/74365777-6968ba80-4dd7-11ea-8413-a25420170048.png)
Yeap

**Comment by brunojs02** [comment]
Where these configs is stored?

**Comment by brunojs02** [comment]
This config must be in firebase remote config, because when the app starts, the configurations is loaded and persisted to redux.
Probably the error is occurring because when i use hook use-fetch i need to know the themoviedb apikey, for this i load from another hook called use-remote-config, that is stored in redux.

**Comment by MacMillan13** [comment]
@brunojs02 This config is stored in src/constants/firebase-constants.js

**Comment by brunojs02** [comment]
@MacMillan13 pull to update the project and put theses configurations on firebase remote config :)

**Comment by brunojs02** [comment]
@MacMillan13 the file that u update with keys and so on, is used to recovery the config from firebase

**Comment by MacMillan13** [comment]
@brunojs02 read about how to do it. Thanks. Tell me plse is it also necessary to ios? or this app just to android?

**Comment by brunojs02** [comment]
@MacMillan13 to configure the app and firebase, create a account in firebase, create a project, after u need create  a app inside firebase, choose between android/ios, and use package/bundleId com.rnmovies, after u download the json/plist file (see before run instructions)..
This app run on both, and u configure remote config only once, the difference is that u need configure 2 the package/bundleId

**Comment by MacMillan13** [comment]
@brunojs02 I did it before write this issue. I had downloaded google-services.json. Try to understand where i have to write configs

**Comment by MacMillan13** [comment]
@brunojs02 sorry. it's my first expirience with mobile, maybe i don't understand something...
![Screenshot from 2020-02-12 22-15-12](https://user-images.githubusercontent.com/18086617/74373422-1990f000-4de5-11ea-9003-d87717589f94.png)
I have added, but also have this error...

**Comment by brunojs02** [comment]
could u compact the project with your google-services.json and send me to bruno.js02@gmail.com?

**Comment by MacMillan13** [comment]
@brunojs02 allredy

**Comment by brunojs02** [comment]
@MacMillan13 i found the errors, u must reverse the files:
- src/screens/home/components/popular-movies/PopularMovieList.js
- src/constants/firebase-constants.js
ps: the constants file is not used to store values, just for recovery them from redux.

**Comment by MacMillan13** [comment]
@brunojs02 thanks so much, this is resolved. But I see just a home tab(without images), other tabs is empty, is it correct?

**Comment by brunojs02** [comment]
@MacMillan13 the other tabs empty is correct, i need finish this project, but i dont have time in the moment.
Your home is different from this [#585291053](https://github.com/brunojs02/react-native-movies-app/issues/2#issuecomment-585291053)

**Comment by MacMillan13** [comment]
@brunojs02 Thank to you. I have figured out

**Comment by thangtx86** [comment]
I created the movie api key and download google-services.json then i run the project success, but i can not receiver data from the movie api db.So I don't know what's wrong with api configuration,
Then i created api key and i put it to `firebase-constants.js` like as: 
![Screen Shot 2022-06-22 at 14 36 06](https://user-images.githubusercontent.com/36811728/174973114-f62aec0b-9381-49da-9202-b01aabd0b2fe.png)
So hope you guys help me this problem. thanks you.
