### ISSUE TITLE
Failed prop type :  the prop 'children' is marked as required in 'Container', but it's valus is 'undefined'.

### ISSUE THREAD

**Issue by BlackburnSS7** [brunojs02/react-native-movies-app#4]
![Capture](https://user-images.githubusercontent.com/61349839/87614512-21442000-c708-11ea-881a-b623bb342ef9.PNG)
when i click on the search icon to search for a movie this happens 
Please help !

**Comment by brunojs02** [comment]
It's happens because only Home and Profile screen are created in [tab navigation](https://github.com/brunojs02/react-native-movies-app/blob/master/src/navigation/Main.js#L10-L16).

**Comment by BlackburnSS7** [comment]
can you help me create the search component please !


Le jeu. 16 juil. 2020 à 02:30, Bruno Santos <notifications@github.com> a
écrit :
